In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [5]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [2]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [4]:
X_train, X_test, y_train, y_test

(array([[ 0.,  0.,  6., ...,  0.,  0.,  0.],
        [ 0.,  0.,  4., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  3.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  3.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.]]),
 array([[ 0.,  0.,  9., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 12.,  8.,  0.],
        [ 0.,  2., 10., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  3., 12., ...,  6.,  0.,  0.],
        [ 0.,  0.,  3., ...,  0.,  0.,  0.]]),
 array([5, 5, 9, ..., 1, 7, 9]),
 array([5, 6, 7, 3, 2, 0, 1, 8, 9, 7, 9, 9, 2, 3, 6, 6, 4, 1, 0, 5, 8, 9,
        4, 4, 6, 3, 5, 8, 1, 1, 8, 9, 5, 9, 7, 8, 2, 6, 7, 0, 7, 7, 1, 3,
        0, 8, 2, 7, 0, 8, 8, 9, 1, 0, 7, 7, 1, 9, 6, 1, 2, 1, 7, 8, 8, 1,
        0, 2, 1, 0, 1, 7, 6, 4, 4, 6, 3, 3, 0, 9, 6, 4, 0, 1, 7, 8, 1, 6,
        8, 4, 8, 9, 8, 4, 7, 9, 6, 4, 8, 5, 6, 3, 4, 7, 2, 4, 2, 5, 9, 2,
        0, 3, 5, 6, 7, 3, 0

In [1]:

lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

NameError: name 'LogisticRegression' is not defined

In [4]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3425925925925926

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975925925925926

In [7]:
#KFOLD
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
#Making a function
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [12]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9907407407407407

In [15]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

D:\AnaCONDA1\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [16]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [17]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [18]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [19]:
scores_rf

[0.9365609348914858, 0.9465776293823038, 0.9148580968280468]

In [20]:
#One lines
#cross_val_score uses stratifield kfold by default
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [22]:

cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [23]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93322204, 0.94323873, 0.9081803 ])

In [24]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8737150837988826

In [25]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9348882681564245

In [26]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.938234016139044

In [ ]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)